# Class Actvities #
#Reg No : 23-NTU-CS-1029 , Class: BSCS 7th A , Name:Hadia Usman
# Task 1 #
## Loading The Dataset ##
### 1 Mannual Data Creation ###
"""
import pandas as pd 
#### Create a Data set using Dictonary and then print it
dic_data = {'Name': ['Alice', 'Bob', 'Diana', 'Charlie', 'Fatima','Ali'],
        'Age':[25, 30, 35, 28 , 24 , 26 ],
        'City': ['Lahore', 'Faisalabad', 'Karachi', 'Multan','Islamabad','Rawlapindi'],
        'Salary':[50000, 60000 , 70000 , 55000 , 80000 , 82000]
        }
df_mannual = pd.DataFrame(dic_data)
print("Mannual DataFrame:")
print(df_mannual)
"""
#Task2 
##Loading data From CSV File and Oline File and printing first 5 lines
"""
import pandas as pd
#Load CSV Car file using .read_csv 
df_csv_file = pd.read_csv('cars.csv')
print("CSV_CAR_DATA:")
print(df_csv_file.head())
#Load CSV from online source From a URL
online_source_csv_url= "https://raw.githubusercontent.com/datasets/covid-19/master/data/time-series-19-covid-combined.csv"
df_csv_online = pd.read_csv(online_source_csv_url)
print("\n Online CSV File Data:")
print(df_csv_online.head())
"""
#Task 3
# Loading JSON FILE Data using .read_json and also from online source and printing first 5 line
"""
import pandas as pd
df_json_attendance_data = pd.read_json('attendance.json')
print("JSON ATTENDANCE DATA:")
print(df_json_attendance_data.head())
# Loading JSON from online resource
json_data_url = "https://jsonplaceholder.typicode.com/users"
df_online_json_data = pd.read_json(json_data_url)
print("Online Json Data:")
print(df_online_json_data.head())
"""
#Task 4
##Loading Data From Excel File using .read_excel
"""
import pandas as pd
# load data form excel file and printing first lines
df_excel_data= pd.read_excel('extra.xlsx')
print("Excel Data:")
print(df_excel_data.head())
"""
#Task 5 
## Loading Data From Text File 
"""
import pandas as pd 
#load data from text file using .read_csv with custom delimeter used
df_text_data = pd.read_csv('data.txt', delimiter='\t')
print("Text File Data")
print(df_text_data.head())
"""
#Task6
##Creating Sample Data With using Numpy Library
"""
import pandas as pd
import numpy as np
# Create data set using dictonary and numpy array 
np.random.seed(42)
#Create mannual data and using .DataFrame and printing first lines
data = {
    'ID': range(1,101),
    'Score':np.random.randint(50,100,100),
    'Height':np.random.normal(170,10,100).round(1),
    'Weight':np.random.normal(70,5,100).round(1)
}
df_numpy_data = pd.DataFrame(data)
print("Data Generated by Numpy is:")
print(df_numpy_data.head())
"""
#Task 7
# Loading Data Using SkLearn
"""
from sklearn import datasets
# loading the iris dataset from the datasets using datasets.load_iris
iris_dataset = datasets.load_iris()
# Show the X data menas the features only 5 rows
print("Features only 5 rows:")
print(iris_dataset.data[:5])
# Show the target values y of the dataset of first 5 rows
print("Traget y Data of 5 rows")
print(iris_dataset.target[:5])
"""

###Data Preprocessing 
#Task 8 Handling Missing Values 
"""
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
##Creating a mannual dataset with missing values
data1 = {
    'A': [1, 2, None, 4, 5, 6 ],
    'B': [7,None , 8 , 9 , 10 ,11],
    'C': [12, 13 ,14 ,15 ,16 ,None]
    
}
df_data = pd.DataFrame(data1)
# Original Data is 
print("Original DataFrame:")
print(df_data)
### After seeing original data know handle missing values by using 
###   methods either drop row with missing values or coloumsn with missing values
###   or fill the miisng values with 0 , mean ,median or mode

##Method 1 : Drop Rows with Missing Values using dropna function and axis = 0 (for rows)
df_dropna__rows = df_data.dropna(axis=0)
##Method 2 : Drop Coloumns with Missing Values using dropna here also and axis = 1 (for coulmns)
df_dropna__columns = df_data.dropna(axis=1)
###Method 3 : Fill Missing Value with median using fillna
df_fill__median = df_data.fillna(df_data.median())
###Now displaying all the values when did method 1 for removing rows 
###  with Missing Values , Then Method 2 of  removig columns with
###  missing values and last method 3 to fil the missing values

print("\n DataFrame after droping rows with missing values")
print(df_dropna__rows)
print("\n DataFrame after dropping coloumns with missing values")
print(df_dropna__columns)
print("\n DatFrame after filling te missing values iwth the median know")
print(df_fill__median)
"""
###Handling categorical values doing encoding as ML mostly accept numeric 
###values not text using Ordinal / Manuual Mapping , Label Encoding and one hot Encoding"""


#Task 9
##Handling Categorical Encoding
"""
import pandas as pd
##Mannual Encoding Example

Mannual_mapping = {'h':1 , 'u':2 , 't':3 , 'v': 4}
features_x=pd.DataFrame({'Type':['h','u','h','u','t','v','t']})
features_x['Type']= features_x['Type'].map(Mannual_mapping)
print("\n Mannual Encoding Types:")
print(features_x.groupby('Type').size())
"""
#Task 10
##Using Label Encoder Know
"""
from sklearn.preprocessing import LabelEncoder
import pandas as pd

features_df_x = pd.DataFrame({'RegionName': ['North','South','East','West','South',
                                             'North','East']})
##Now applynig the labelEncoder
labelencoder = LabelEncoder()
features_df_x['Regions'] = labelencoder.fit_transform(features_df_x['RegionName'])
print("\n Label Encoder Regions:")
print(features_df_x.value_counts())
"""
###Using Hot Encoder know we will
#Task 11
"""
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

Features__x= pd.DataFrame({'Method':['Method1', 'Method2','Method1',
                                     'Method3','Method2','Method3','Method1']})

df_get_one_hot_encoder= pd.get_dummies(Features__x['Method'])
print("\n One Hot Encoder DataFrame")
print(df_get_one_hot_encoder.value_counts())
"""
#Task12
##Ordinal Encoding
"""
from sklearn.preprocessing import OrdinalEncoder
import pandas as pd
data_2 = pd.DataFrame({'Education':['HighSchool', 'Bachelors','Masters','Phd','Bachelors']})
###Mannualy defining what te order
data_order = [['HighSchool','Bachelors','Masters','Phd']]
Ordianalencoder= OrdinalEncoder(categories=data_order)
data_2['Education_Encoded']=Ordianalencoder.fit_transform(data_2[['Education']])
print(data_2)

"""
#Task 13 Find outliers
###Handling Outliers using IOR or LOG Transformation
"""
import matplotlib.pyplot as plt 
import numpy as np 

#Data with an outlier inside it 
outlier_data = [10 ,12 ,14 ,15 , 13 ,16 ,11 , 100]
#Plotting boxplot
plt.boxplot(outlier_data)
plt.title("Outlier Visualization")
plt.show()
"""
#Task 14 Handling outliers using IQR 
"""
import pandas as pd
data_3= pd.DataFrame({"Income":[25000 , 27000, 26000, 28000 , 50000, 24000, 23000]})
Q1  = data_3['Income'].quantile(0.25)
Q3  = data_3['Income'].quantile(0.75)
IQR = Q3 -Q1
lower_limits= Q1 - 1.5 *IQR
upper_limits= Q3 + 1.5 *IQR
outliers = data_3[(data_3['Income']< lower_limits) | (data_3['Income'] > upper_limits)]
print(outliers)
data_cleared = data_3[(data_3['Income']>=lower_limits) & (data_3['Income']<=upper_limits)]
print(data_cleared)
#Task 15 using Log Transformation 
import numpy as np
data_3['Income_log']=np.log(data_3['Income'])
print(data_3)
"""
#Task 15 
#Feature scaling 
"""
import pandas as pd
from sklearn.preprocessing import StandardScaler , MinMaxScaler
Age_Income_data = pd.DataFrame({'Age':[22,25,47,45,35,60],
                         'Income':[25000,32000,55000,95000,60000,15000]})

##Rescaling data to the mean 0 and standard deviation 1
Std_scaler = StandardScaler()
data_Standarded = Std_scaler.fit_transform(Age_Income_data)
print("Standard data:")
print(data_Standarded)

##Normalization: Rescaling data into the fixed range like between 0 and 1
min_max_scaler = MinMaxScaler()
data_normalized= min_max_scaler.fit_transform(Age_Income_data)
print('\n MinMax Data')
print(data_normalized)
"""
#Task16
"""
#Faeture selection , Feature Enginnering (Extract useful information from the features)
# and Dimensionality Reduction using PCA (Principle Component Analysis)
import pandas as pd
from sklearn.decomposition import PCA
#Mannual Sample Dataset
dataset = pd.DataFrame({
    'Height_cm':[150,160,170,180,190,200],
    'Height_inch':[59,63,67,71,75,79],
    'Weight':[50,60,70,80,90,100],
    'Date':['2026-01-05','2026-02-06','2026-03-10','2026-04-15','2026-05-20','2026-06-25']
})

#Feature selction (Init we removes those features which are hight corelated
# as redundant information usig corr() to find corelation)
correlation = dataset[['Height_cm','Height_inch','Weight']].corr()
print("Corelation Matrix \n",correlation)
# AS we see height_inch and Height_cm are corelated so we drop one using drop function
data_new = dataset.drop("Height_inch", axis = 1)
print("\nDate After Feature Selection\n",data_new)

##Feature Engineering
#(Creting new and useful features form existion one)
#Exmaple 1 : Combing weight and height feature to make new feature BMI
data_new['BMI']=data_new['Weight']/((data_new['Height_cm']/100)**2)
#Exmpale 2 : Extract day of week from date column
data_new['Date']=pd.to_datetime(data_new['Date'])
data_new['day_of_week']=data_new['Date'].dt.day_name()
print("\n Data after Feature engineering:\n",data_new)

#Dimensionality reduction PCA
#Reduce no.of numeric fetaures while reserving most of information 
numeric_features = data_new[['Height_cm','Weight','BMI']]
pca = PCA(n_components=2)
reduced_data = pca.fit_transform(numeric_features)
print("\n Data after PCA reduced to 2 xomponents:\n", reduced_data)
"""
#Task17
##Handling Imbalanced Data 
"""
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
##Creating Mannual Sample imbalanced Dataset
###In it we have 900 disease cases and 100 no disease cases
import numpy as np
np.random.seed(42)
f_x = pd.DataFrame({
    'Feature1': np.random.rand(1000),
    'Feature2': np.random.rand(1000)
})
#0  is for No Disease and 1 is for Disease
f_y= pd.Series([0]*900 + [1]*100)
print("Original class Distribution:\n", f_y.value_counts())
##Split into Tarin/Test First  Note the resampleing had to be applied only
##on the training data
X_train , X_test , Y_train ,Y_test = train_test_split ( f_x ,f_y,test_size=0.2,
                                                      random_state=42,stratify=f_y)

##Oversmapling Resolve by generating more synthetic sample of minority class
smote = SMOTE(random_state=42)
X_train_smote , Y_train_smote= smote.fit_resample(X_train,Y_train)
print("After Smote Overlapping : \n", Y_train_smote.value_counts())

##Undersampling Resolve by reducing no of samples of majority class
undersampler = RandomUnderSampler(random_state=42)
X_Train_Under , Y_Train_Under = undersampler.fit_resample(X_train,Y_train)
print("\nAfter UnderSampling:\n",Y_Train_Under.value_counts())

###Class Weightining In it Datasets remain same the model gives more 
###importance to minority class internally
model_Logistic = LogisticRegression(class_weight='balanced')
model_Logistic.fit(X_train,Y_train)

print("\n Class wiegthing Model trained on Original Imbalanced Data\n")
print("Model Automaticalay weights the Minority class more heavily during Training ")
"""
##Task 18
##Data Visulaization using matplot lib now doing for years and population
"""
import matplotlib.pyplot as plt
years = [1994 , 1995 , 1998 , 2000 ,2004 , 2005]
population = [2.59 , 3.69 , 5.33 , 6.99 , 7.55 , 8.90]
plt.plot(years,population)
plt.show()
plt.scatter(years,population)
plt.show()
"""
##Task 19 
###Labels , legends and Titles used in above example now 
"""
import matplotlib.pyplot as plt
years = [1994 , 1995 , 1998 , 2000 ]
population = [2.59 , 3.69 , 5.33 , 6.99 ]
plt.plot(years,population,label='Population 1')
population2 = [4.44 , 3.22 , 5.55 , 6.88 ]
plt.plot(years,population2, label='Population 2')
plt.xlabel('Independent Variable')
plt.ylabel('Dependent Varaible')
plt.title('Years and Populations Graph')
plt.legend()
plt.show()
"""
#Task20 
##Now using grid in it  and fill to fill that area rest of the example and code
##is same 
"""
import matplotlib.pyplot as plt
years = [1994 , 1995 , 1998 , 2000 ]
population = [2.59 , 3.69 , 5.33 , 6.99 ]
plt.plot(years,population,'r',label='Population 1',linewidth=5)
population2 = [4.44 , 3.22 , 5.55 , 6.88 ]
plt.plot(years,population2, 'c',label='Population 2', linewidth=5)
plt.xlabel('Independent Variable')
plt.ylabel('Dependent Varaible')
plt.title('Years and Populations Graph')
plt.legend()
plt.grid(True , color = 'k')
plt.fill_between(years,population,0,color='blue')
plt.show()
"""
#Task21 Using Histogram
"""
import matplotlib.pyplot as plt
val = [1.1 , 1.3 , 2.1 , 3.3 ,2.4  ,6.5 , 6.6 , 7.7 , 8.8 , 9.9 ,4.2 ,5.3 ]
plt.hist(val , bins=3)
plt.show()
"""
#Task22
##Exploring Dataset
""""
from sklearn.datasets import fetch_olivetti_faces
###Fetching faces data
faces = fetch_olivetti_faces()
faces.keys()
#Samples and features
n_samples , n_features = faces.data.shape
print((n_samples,n_features))
print(faces.images.shape)
print(faces.data.shape)
print(faces.DESCR)


X_feature , Y_target = faces.data ,faces.target
import matplotlib.pyplot as plt 
##Showing image present at The 5th index
plt.imshow(faces.images[5],cmap='gray')
plt.title(f"Face ID:{faces.target[5]}")
plt.axis('off')
plt.show()
plt.figure(figsize=(6,6))
for i in range(16):
    plt.subplot(4,4,i+1)
    plt.imshow(faces.images[i],cmap='gray')
    plt.axis("off")
    plt.title(faces.target[i])
plt.show()
"""
#Task23 
##Iris Dataset Exploring
"""
from sklearn.datasets import load_iris
iris_d = load_iris()
print(iris_d.keys())
print(iris_d["target_names"])
n_samples , n_features_x = iris_d.data.shape
print("Number of sample:",n_samples)
print("Number of features:", n_features_x)
print("Features_Name:",iris_d.feature_names)
print("Target_Name:",iris_d.target_names)
print("Dimensionality of Input:",iris_d.data.shape)
print("Dimensionality of Output:", iris_d.target.shape)
print("First 5 rows of input:",iris_d.data[1:5])
print("Target Data:", iris_d.target)
"""


################# Activites  ########################

#### Activity 1 ####
#Create Province data with given coloums of proivnce population litercay rate 
# and Region 
"""
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
import matplotlib.pyplot as plt

Provinces_Data = pd.DataFrame({'Province':['Punjab','Sindh','KPK','Balochistan'],
                               'Population(millions)':[6.5 , None , 3.2, 5.5],
                               'LiteracyRate(%)':[68.8, 50.5 ,None , 250.8],
                               'Reigon':['North','South','East','West']})
print(Provinces_Data)

##Handling Miisng Values with droping  row using dropna or fiiling using fillna using subest to specify specifci row
province_data_dropna_rows = Provinces_Data.dropna(subset=['Population(millions)'],axis=0)
print("\nHandling Missing Data with Rows using Dropna:\n",province_data_dropna_rows)

###Filling The missing data with median using fillna
province_data_fillna = Provinces_Data['LiteracyRate(%)'].fillna(Provinces_Data['LiteracyRate(%)'].median())
print("\nMissing Values filled using fillna with median:\n",province_data_fillna)

###Encoding Region column with lbale and onehot encoding
##First LabelEncoder
labelenc = LabelEncoder()

Provinces_Data['RegionsName']=labelenc.fit_transform(Provinces_Data['Reigon'])
print("\n Label Encoded Regions:\n")
print(Provinces_Data.value_counts())


###Now One hot encoder
df_one_hot_enc = pd.get_dummies(Provinces_Data['Reigon'])
print('\n One Hot Encoder DataFrame:\n')
print(df_one_hot_enc.value_counts())


####Now viuslaize population vs lietracy rate 
plt.scatter(Provinces_Data['Population(millions)'],Provinces_Data['LiteracyRate(%)'])

for i , r in Provinces_Data.iterrows():
    plt.text(r['Population(millions)'],r['LiteracyRate(%)'], r['Province'])

plt.xlabel("Population(millions)")
plt.ylabel("LiteracyRate(%)")
plt.title("Population vs Literacy Rate")
plt.show()

plt.boxplot(province_data_fillna)
plt.title("Detect Oulier if any")
plt.ylabel("Literacy Rate")
plt.show()
"""

#Activity2

"""
# Creating RANDOM DATA FOR 100 STUDENTS
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
np.random.seed(42)
Students_data = pd.DataFrame({
    'ID': np.arange(201,301),
    'Math':np.random.randint(45,100,size=100),
    'Science':np.random.randint(55,100,size=100),
    'English':np.random.randint(75,100,size=100),
    'Grade':np.random.choice(['A','B','C'],size=100)
})

print(Students_data)

###To check for Missing values and fill with mean first we have to crets ths using loc 
###we cannot direct use index with coulmn name in the pandas array 
Students_data.loc[4,'Math'] = np.nan
Students_data.loc[95,'English'] =np.nan 
Students_data.loc[99,'Science'] = np.nan

print(Students_data)

#Handle Missing Marks filling with mean
df_M = Students_data['Math'].fillna(Students_data['Math'].mean()) 
df_E = Students_data['English'].fillna(Students_data['English'].mean()) 
df_S = Students_data['Science'].fillna(Students_data['Science'].mean()) 

###Showing those missing values
print("\n For Math Marks Missing:\n",df_M)
print("\n For English Marks Missing:\n",df_E)
print("\n For Science Marks Missing:\n",df_S)

###Encoding Grade Column
Students_data['Grade_Encoding']=Students_data['Grade'].map({'A':3 , 'B':2 , 'C':1})
print(Students_data[['Grade','Grade_Encoding']])

###Plotting Histogram
plt.hist(df_M,bins=10)
plt.title('Math Marks Using Histogram')
plt.show()

###Total Marks And checking if any outlier
Students_data['Total Marks']=df_M+df_S+df_E
plt.boxplot(Students_data['Total Marks'])
plt.title('High / Less Marks of Students')
plt.show()

##Summarize Findings
Grade_Performed_Best = Students_data.groupby('Grade')['Total Marks'].mean()
print('\nGrade_Performance is:\n',Grade_Performed_Best)
"""
###Activity3

"""

Covid data extract only of Pakistan from url 
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

online_csv_url_link = "https://raw.githubusercontent.com/datasets/covid-19/master/data/time-series-19-covid-combined.csv"
Covid_Data = pd.read_csv(online_csv_url_link)
Pakistan_Covid_Data = Covid_Data[Covid_Data['Country/Region']=='Pakistan']
#print(Pakistan_Covid_Data)


###Handling Missing Value usg drop function as to drop specific column
df_Dropna_PCD = Pakistan_Covid_Data.drop(columns=['Province/State'])
print("\n Data After Handling Missing Value:\n",df_Dropna_PCD)

###Line plot
plt.plot(df_Dropna_PCD['Date'],df_Dropna_PCD['Confirmed'])
plt.xlabel('Date')
plt.ylabel('Confimed Cases')
plt.title("Covid Cases Over Time")
plt.show()

###Finding the one data with highest case
maximum_case_report = df_Dropna_PCD['Confirmed'].idxmax()
###Now we have to extract that sepecifc row case and date
row_max = df_Dropna_PCD.loc[maximum_case_report]
print("\nDate with Highest Confirmed Cases\n")
print("\n Date: ",row_max['Date'])
print("\n Highest cases:",row_max['Confirmed'])

###Outlier Detect 
plt.boxplot(df_Dropna_PCD['Confirmed'])
plt.title("Outlier in Confirmed cases")
plt.show()
"""
#Activity4

"""
##Load three given datasets and merge them
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder

Student_data = pd.read_csv('students.csv')
Attendance_data = pd.read_json('attendance.json')
Extra_data= pd.read_excel('extra.xlsx')

Two_data_megre = pd.merge(Student_data,Attendance_data,on='Name')
Combined_merged_data=pd.merge(Two_data_megre,Extra_data, on='Name')
print(Combined_merged_data)
##Scatter Plot also Highlight if greater than 70 
Highest_Marks_HighLight = Combined_merged_data[Combined_merged_data['Marks']> 70]
plt.scatter(Combined_merged_data['Attendance'],Combined_merged_data['Marks'],c=['orange' if mark > 70 else  'Gray' for mark in Combined_merged_data['Marks'] ] )

plt.xlabel("Attendance")
plt.ylabel("Marks")
plt.title("Attendance vs Marks (Marks > 70 Orange)")
plt.show()

###One Hot encdoing
one_hot_enc = pd.get_dummies(Combined_merged_data['Name'])
print("\n One Hot Encoding\n ")
print("\n data shape : \n",one_hot_enc.shape)

print(one_hot_enc.head())
"""
#Actvity 5

##Have this given data and perform necessary operation
"""
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data_given = pd.DataFrame({
    'Name':['Ahsan','Hira','Bilal','Zara','Salman','Mahnoor'],
    'Age':[25,27,35,29,None,40],
    'Salary':[50000,None,75000,2000000,60000,90000],
    'Department':['IT','Finance','IT','HR','Finance','IT']
    
})
print(data_given)

##Handle miising values properly using fillna medain 
df_fillna_age=data_given['Age'].fillna(data_given['Age'].median())
df_fillna_Salary=data_given['Salary'].fillna(data_given['Salary'].median())
print("\nAfter handling missing values\n")
print("\nFor Age :\n",df_fillna_age)
print("\nFor Salary :\n",df_fillna_Salary)

##Department encoded 
data_given['Department_Encoded']= data_given['Department'].map({'IT':1,'Finance':2 ,'HR':3})
print("\nDepartment Encoded\n")
print(data_given[['Department','Department_Encoded']])

###Zara Salary is oulier or trated that way or not 
plt.boxplot(df_fillna_Salary)
plt.title("Zara Salary as outlier")
plt.show()
"""
#Activity 6

"""
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

###Exploring breast cancer dataset

breast_cancer_data = load_breast_cancer()
print(breast_cancer_data.keys())
print(breast_cancer_data["target_names"])
n_samples , n_features = breast_cancer_data.data.shape
print("Number of samples:",n_samples)
print("Number of features:",n_features)
print("Feature Name:",breast_cancer_data.feature_names)
print("Target Name:",breast_cancer_data.target_names)
print("Shape of input:",breast_cancer_data.data.shape)
print("Shape of Output:",breast_cancer_data.target.shape)
print("First 5 rows:",breast_cancer_data.data[1:5])
print('Target Data:',breast_cancer_data.target)

##First converting it to the dataframe 
df_data = pd.DataFrame(breast_cancer_data.data, columns=breast_cancer_data.feature_names)

###Introdcng artifical nan values in mean_radius 
df_data.loc[0:4,'mean radius']=np.nan
##See that 
print("\nAfter Introducting 5 artifical Nan values in mean radius:\n",df_data['mean radius'].head(7))

##Now Adding fillna function so recoer it usng mean as the outlier is 
##not that big so so do not need to use median

df_data['mean radius']= df_data['mean radius'].fillna(df_data['mean radius'].mean())
print("\nAfter Filling Thos values using Fillna with mean:\n",df_data['mean radius'].head(7))

###Targer dataset imbaalnced or not 
df_data['Target']=breast_cancer_data.target
print("\nClass counts Before:\n")
print(df_data['Target'].value_counts())

##Will do oversampling crete sytheic data or minority class
X_f = df_data.drop(columns=['Target'])
Y_t = df_data['Target']

smote_data= SMOTE(random_state=42)
X_resample, Y_resample = smote_data.fit_resample(X_f,Y_t)
print("\n Class Count After Oversampling is :\n")
print(pd.Series(Y_resample).value_counts())

###Ouliers Handles using IQR for mean radius and mean texture
Q1_radius = df_data['mean radius'].quantile(0.25)
Q3_radius = df_data['mean radius'].quantile(0.75)
IQR_radius = Q3_radius -Q1_radius

lower_limit_radius = Q1_radius - 1.5 * IQR_radius
upper_limit_radius = Q3_radius + 1.5 * IQR_radius

outliers_radius = df_data[(df_data['mean radius'] < lower_limit_radius) | (df_data['mean radius'] > upper_limit_radius)]
print("\nMean radius Outliers\n:",outliers_radius)

##For texture 
Q1_texture = df_data['mean texture'].quantile(0.25)
Q3_texture = df_data['mean texture'].quantile(0.75)
IQR_texture = Q3_texture -Q1_texture

lower_limit_texture = Q1_texture - 1.5 * IQR_texture
upper_limit_texture = Q3_texture + 1.5 * IQR_texture

outliers_texture = df_data[(df_data['mean texture'] < lower_limit_texture) | (df_data['mean texture'] > upper_limit_texture)]
print("\nMean texture Outliers\n:",outliers_texture)

##Visualizeing it 
plt.boxplot([df_data['mean radius'],df_data['mean texture']],tick_labels=['mean radius', 'mean texture'])
plt.title("Outlier Detection ")

plt.ylabel("Values")
plt.show()

###Mean are log transformation 
df_data['Mean area Log']= np.log(df_data['mean area'])

##Plot in histogram
df_data[['mean area','Mean area Log']].hist(bins= 30, figsize=(10,4))
plt.show()

##Standard Scalar used 

X_feat = df_data.drop(['Target' , 'Mean area Log'], errors = "ignore")
Y_targets = df_data['Target']
#Using Standard Scalar too scale features have value of mean 0 and 
# Standard deviation 1 
Standard_scalar = StandardScaler()
X_f_scaled = Standard_scalar.fit_transform(X_feat)
print(X_f_scaled[:5])

## We use this standard feature sacling setp because model like SVM , KNN 
# used to calculate distance if one column has high numbers and other less
# so the result will be controlled by high one which is not good That why we do this


#PCA dimension reduction
pca = PCA(n_components=2)
X_f_PCA = pca.fit_transform(X_f_scaled)
plt.scatter(X_f_PCA[:,0],X_f_PCA[:,1],c=Y_targets,cmap='gray',alpha=0.7)
plt.xlabel("PCA COMPONENT 1")
plt.ylabel("PCA COMPONENT 2")
plt.title("PCA OF breast Cancer")
plt.show()

###Train and test on Two Like KNN and Random forest Classifier
X_train,X_test,Y_train,Y_test=train_test_split(X_f_scaled,Y_targets,test_size=0.2,random_state=42)
k_nearest_neighbour = KNeighborsClassifier()
k_nearest_neighbour.fit(X_train,Y_train)
print("\nKNN ACCURACY :\n ", accuracy_score(Y_test,k_nearest_neighbour.predict(X_test)))


#rANDOM fOREST 
random_forest_class = RandomForestClassifier()
random_forest_class.fit(X_train,Y_train)
print("\nRandomForest ACCURACY :\n ", accuracy_score(Y_test,random_forest_class.predict(X_test)))
"""